/**
 * --------------------------------------------------------
 * This demo was created using amCharts V4 preview release.
 * 
 * V4 is the latest installement in amCharts data viz
 * library family, to be released in the first half of
 * 2018.
 *
 * For more information and documentation visit:
 * https://www.amcharts.com/docs/v4/
 * --------------------------------------------------------
 */


am4core.useTheme(am4themes_animated);
var chart = am4core.create("chartdiv", am4charts.ChordDiagram);


// colors of main characters
chart.colors.saturation = 0.45;
chart.colors.step = 3;
var colors ={}

// data was provided by: https://www.reddit.com/user/notrudedude

chart.data = [
// node property fields take data from data items where they are first mentioned, that's 
// why we add empty data items at the beginning and set colors here

// real data
{"from":"  ","to":"  ","value":250,"color":"#FFFFFF"},
{"from":"Sin Pueblos","to":"Sin Pueblos","value":0,"color":"#52718c"},
{"from":"Cochimí","to":"Cochimí","value":0,"color":"#52718c"},
{"from":"Cucapá","to":"Cucapá","value":0,"color":"#52718c"},
{"from":"Kiliwa","to":"Kiliwa","value":0,"color":"#52718c"},
{"from":"Ku'ahl","to":"Ku'ahl","value":0,"color":"#52718c"},
{"from":"Pa Ipai","to":"Pa Ipai","value":0,"color":"#52718c"},
{"from":"Kumiai","to":"Kumiai","value":0,"color":"#52718c"},
{"from":"Pápago","to":"Pápago","value":0,"color":"#52718c"},
{"from":"Kikapú","to":"Kikapú","value":0,"color":"#52718c"},
{"from":"Seri","to":"Seri","value":0,"color":"#52718c"},
{"from":"Ixil","to":"Ixil","value":0,"color":"#52718c"},
{"from":"Kaqchikel","to":"Kaqchikel","value":0,"color":"#52718c"},
{"from":"Q'Eqchi'","to":"Q'Eqchi'","value":0,"color":"#52718c"},
{"from":"Mixteco","to":"Mixteco","value":0,"color":"#52718c"},
{"from":"Yaqui","to":"Yaqui","value":0,"color":"#52718c"},
{"from":"Maya","to":"Maya","value":0,"color":"#52718c"},
{"from":"Ayapaneco","to":"Ayapaneco","value":0,"color":"#52718c"},
{"from":"K'iche'","to":"K'iche'","value":0,"color":"#52718c"},
{"from":"Chontal de Tabasco","to":"Chontal de Tabasco","value":0,"color":"#52718c"},
{"from":"Lacandón","to":"Lacandón","value":0,"color":"#52718c"},
{"from":"Chuj","to":"Chuj","value":0,"color":"#52718c"},
{"from":"Oluteco","to":"Oluteco","value":0,"color":"#52718c"},
{"from":"Popoluca de la Sierra","to":"Popoluca de la Sierra","value":0,"color":"#52718c"},
{"from":"Sayulteco","to":"Sayulteco","value":0,"color":"#52718c"},
{"from":"Texistepequeño","to":"Texistepequeño","value":0,"color":"#52718c"},
{"from":"Akateko","to":"Akateko","value":0,"color":"#52718c"},
{"from":"Teko","to":"Teko","value":0,"color":"#52718c"},
{"from":"Awakateko","to":"Awakateko","value":0,"color":"#52718c"},
{"from":"Huave","to":"Huave","value":0,"color":"#52718c"},
{"from":"Jakalteko","to":"Jakalteko","value":0,"color":"#52718c"},
{"from":"Q'Anjob'Al","to":"Q'Anjob'Al","value":0,"color":"#52718c"},
{"from":"Tojolabal","to":"Tojolabal","value":0,"color":"#52718c"},
{"from":"Chichimeca","to":"Chichimeca","value":0,"color":"#52718c"},
{"from":"Ch'ol","to":"Ch'ol","value":0,"color":"#52718c"},
{"from":"Chontal de Oaxaca","to":"Chontal de Oaxaca","value":0,"color":"#52718c"},
{"from":"Mayo","to":"Mayo","value":0,"color":"#52718c"},
{"from":"Pame","to":"Pame","value":0,"color":"#52718c"},
{"from":"Zoque","to":"Zoque","value":0,"color":"#52718c"},
{"from":"Guarijío","to":"Guarijío","value":0,"color":"#52718c"},
{"from":"Mame","to":"Mame","value":0,"color":"#52718c"},
{"from":"Pima","to":"Pima","value":0,"color":"#52718c"},
{"from":"Huasteco","to":"Huasteco","value":0,"color":"#52718c"},
{"from":"Matlatzinca","to":"Matlatzinca","value":0,"color":"#52718c"},
{"from":"Tlahuica","to":"Tlahuica","value":0,"color":"#52718c"},
{"from":"Ixcateco","to":"Ixcateco","value":0,"color":"#52718c"},
{"from":"Mazahua","to":"Mazahua","value":0,"color":"#52718c"},
{"from":"Mixe","to":"Mixe","value":0,"color":"#52718c"},
{"from":"Chocholteco","to":"Chocholteco","value":0,"color":"#52718c"},
{"from":"Cuicateco","to":"Cuicateco","value":0,"color":"#52718c"},
{"from":"Tepehua","to":"Tepehua","value":0,"color":"#52718c"},
{"from":"Tepehuano del norte","to":"Tepehuano del norte","value":0,"color":"#52718c"},
{"from":"Tseltal","to":"Tseltal","value":0,"color":"#52718c"},
{"from":"Tzotzil","to":"Tzotzil","value":0,"color":"#52718c"},
{"from":"Tarahumara","to":"Tarahumara","value":0,"color":"#52718c"},
{"from":"Tecuate","to":"Tecuate","value":0,"color":"#52718c"},
{"from":"Chatino","to":"Chatino","value":0,"color":"#52718c"},
{"from":"Popoloca","to":"Popoloca","value":0,"color":"#52718c"},
{"from":"Amuzgo","to":"Amuzgo","value":0,"color":"#52718c"},
{"from":"Mazateco","to":"Mazateco","value":0,"color":"#52718c"},
{"from":"Tepehuano del sur","to":"Tepehuano del sur","value":0,"color":"#52718c"},
{"from":"Tlapaneco","to":"Tlapaneco","value":0,"color":"#52718c"},
{"from":"Totonaco","to":"Totonaco","value":0,"color":"#52718c"},
{"from":"Triqui","to":"Triqui","value":0,"color":"#52718c"},
{"from":"Chinanteco","to":"Chinanteco","value":0,"color":"#52718c"},
{"from":"Cora","to":"Cora","value":0,"color":"#52718c"},
{"from":"Zapoteco","to":"Zapoteco","value":0,"color":"#52718c"},
{"from":"Huichol","to":"Huichol","value":0,"color":"#52718c"},
{"from":"Purhépecha","to":"Purhépecha","value":0,"color":"#52718c"},
{"from":"Otomí","to":"Otomí","value":0,"color":"#52718c"},
{"from":"Nahua","to":"Nahua","value":0,"color":"#52718c"},
{"from":" ","to":" ","value":250,"color":"#FFFFFF"},
{"from":"Maiz","to":"Maiz","value":4,"color":"#FFFFFF"},
{"from":"Tuxpeño","to":"Tuxpeño","value":0,"color":"#deb13a"},
{"from":"Vandeño","to":"Vandeño","value":0,"color":"#deb13a"},
{"from":"Olotillo","to":"Olotillo","value":0,"color":"#deb13a"},
{"from":"Bolita","to":"Bolita","value":0,"color":"#deb13a"},
{"from":"Tepecintle","to":"Tepecintle","value":0,"color":"#deb13a"},
{"from":"Celaya","to":"Celaya","value":0,"color":"#deb13a"},
{"from":"Olotón","to":"Olotón","value":0,"color":"#deb13a"},
{"from":"Zapalote Grande","to":"Zapalote Grande","value":0,"color":"#deb13a"},
{"from":"Cónico","to":"Cónico","value":0,"color":"#deb13a"},
{"from":"Nal-tel","to":"Nal-tel","value":0,"color":"#deb13a"},
{"from":"Tabloncillo","to":"Tabloncillo","value":0,"color":"#deb13a"},
{"from":"Elotes Occidentales","to":"Elotes Occidentales","value":0,"color":"#deb13a"},
{"from":"Zapalote Chico","to":"Zapalote Chico","value":0,"color":"#deb13a"},
{"from":"Ratón","to":"Ratón","value":0,"color":"#deb13a"},
{"from":"Nal-tel de Altura","to":"Nal-tel de Altura","value":0,"color":"#deb13a"},
{"from":"Comiteco","to":"Comiteco","value":0,"color":"#deb13a"},
{"from":"Chalqueño","to":"Chalqueño","value":0,"color":"#deb13a"},
{"from":"Elotes Cónicos","to":"Elotes Cónicos","value":0,"color":"#deb13a"},
{"from":"Mushito","to":"Mushito","value":0,"color":"#deb13a"},
{"from":"Dzit Bacal","to":"Dzit Bacal","value":0,"color":"#deb13a"},
{"from":"Tuxpeño Norteño","to":"Tuxpeño Norteño","value":0,"color":"#deb13a"},
{"from":"Ancho","to":"Ancho","value":0,"color":"#deb13a"},
{"from":"Pepitilla","to":"Pepitilla","value":0,"color":"#deb13a"},
{"from":"Cónico Norteño","to":"Cónico Norteño","value":0,"color":"#deb13a"},
{"from":"Chiquito","to":"Chiquito","value":0,"color":"#deb13a"},
{"from":"Conejo","to":"Conejo","value":0,"color":"#deb13a"},
{"from":"Arrocillo Amarillo","to":"Arrocillo Amarillo","value":0,"color":"#deb13a"},
{"from":"Tehua","to":"Tehua","value":0,"color":"#deb13a"},
{"from":"Negrito","to":"Negrito","value":0,"color":"#deb13a"},
{"from":"Cubano Amarillo","to":"Cubano Amarillo","value":0,"color":"#deb13a"},
{"from":"Serrano Mixe","to":"Serrano Mixe","value":0,"color":"#deb13a"},
{"from":"Onaveño","to":"Onaveño","value":0,"color":"#deb13a"},
{"from":"Dulce","to":"Dulce","value":0,"color":"#deb13a"},
{"from":"Tabloncillo Perla","to":"Tabloncillo Perla","value":0,"color":"#deb13a"},
{"from":"Reventador","to":"Reventador","value":0,"color":"#deb13a"},
{"from":"Dulcillo del Noroeste","to":"Dulcillo del Noroeste","value":0,"color":"#deb13a"},
{"from":"Coscomatepec","to":"Coscomatepec","value":0,"color":"#deb13a"},
{"from":"Blando","to":"Blando","value":0,"color":"#deb13a"},
{"from":"Gordo","to":"Gordo","value":0,"color":"#deb13a"},
{"from":"Cacahuacintle","to":"Cacahuacintle","value":0,"color":"#deb13a"},
{"from":"Palomero Toluqueño","to":"Palomero Toluqueño","value":0,"color":"#deb13a"},
{"from":"Zamorano Amarillo","to":"Zamorano Amarillo","value":0,"color":"#deb13a"},
{"from":"Chapalote","to":"Chapalote","value":0,"color":"#deb13a"},
{"from":"Bofo","to":"Bofo","value":0,"color":"#deb13a"},
{"from":"Azul","to":"Azul","value":0,"color":"#deb13a"},
{"from":"Tablilla de Ocho","to":"Tablilla de Ocho","value":0,"color":"#deb13a"},
{"from":"Jala","to":"Jala","value":0,"color":"#deb13a"},
{"from":"Elotero de Sinaloa","to":"Elotero de Sinaloa","value":0,"color":"#deb13a"},
{"from":"Cristalino de Chihuahua","to":"Cristalino de Chihuahua","value":0,"color":"#deb13a"},
{"from":"Serrano","to":"Serrano","value":0,"color":"#deb13a"},
{"from":"Palomero de Chihuahua","to":"Palomero de Chihuahua","value":0,"color":"#deb13a"},
{"from":"Mixeño","to":"Mixeño","value":0,"color":"#deb13a"},
{"from":"Harinoso de Ocho","to":"Harinoso de Ocho","value":0,"color":"#deb13a"},
{"from":"Apachito","to":"Apachito","value":0,"color":"#deb13a"},
{"from":"Motozinteco","to":"Motozinteco","value":0,"color":"#deb13a"},
{"from":"Mixteco","to":"Mixteco","value":0,"color":"#deb13a"},
{"from":"Choapaneco","to":"Choapaneco","value":0,"color":"#deb13a"},
{"from":"Quicheño","to":"Quicheño","value":0,"color":"#deb13a"},
{"from":"Negro de Chimaltenango","to":"Negro de Chimaltenango","value":0,"color":"#deb13a"},
{"from":"Mountain Yellow","to":"Mountain Yellow","value":0,"color":"#deb13a"},
{"from":"Urapeño","to":"Urapeño","value":0,"color":"#deb13a"},
{"from":"Palomero de Jalisco","to":"Palomero de Jalisco","value":0,"color":"#deb13a"},
{"from":"Mushito de Michoacán","to":"Mushito de Michoacán","value":0,"color":"#deb13a"},
{"from":"Complejo Serrano de Jalisco","to":"Complejo Serrano de Jalisco","value":0,"color":"#deb13a"},
{"from":"Amuzgo","to":"Ancho","value":1},
{"from":"Chichimeca","to":"Ancho","value":1},
{"from":"Chinanteco","to":"Ancho","value":1},
{"from":"Chocholteco","to":"Ancho","value":1},
{"from":"Cora","to":"Ancho","value":1},
{"from":"Cuicateco","to":"Ancho","value":1},
{"from":"Huasteco","to":"Ancho","value":1},
{"from":"Huichol","to":"Ancho","value":1},
{"from":"Ixcateco","to":"Ancho","value":1},
{"from":"Matlatzinca","to":"Ancho","value":1},
{"from":"Mazahua","to":"Ancho","value":1},
{"from":"Mazateco","to":"Ancho","value":1},
{"from":"Nahua","to":"Ancho","value":1},
{"from":"Otomí","to":"Ancho","value":1},
{"from":"Pame","to":"Ancho","value":1},
{"from":"Popoloca","to":"Ancho","value":1},
{"from":"Purhépecha","to":"Ancho","value":1},
{"from":"Tecuate","to":"Ancho","value":1},
{"from":"Tepehua","to":"Ancho","value":1},
{"from":"Tlahuica","to":"Ancho","value":1},
{"from":"Tlapaneco","to":"Ancho","value":1},
{"from":"Totonaco","to":"Ancho","value":1},
{"from":"Triqui","to":"Ancho","value":1},
{"from":"Zapoteco","to":"Ancho","value":1},
{"from":"Guarijío","to":"Apachito","value":1},
{"from":"Pima","to":"Apachito","value":1},
{"from":"Tarahumara","to":"Apachito","value":1},
{"from":"Tepehuano del norte","to":"Apachito","value":1},
{"from":"Amuzgo","to":"Arrocillo Amarillo","value":1},
{"from":"Chatino","to":"Arrocillo Amarillo","value":1},
{"from":"Chinanteco","to":"Arrocillo Amarillo","value":1},
{"from":"Chocholteco","to":"Arrocillo Amarillo","value":1},
{"from":"Matlatzinca","to":"Arrocillo Amarillo","value":1},
{"from":"Mazahua","to":"Arrocillo Amarillo","value":1},
{"from":"Nahua","to":"Arrocillo Amarillo","value":1},
{"from":"Otomí","to":"Arrocillo Amarillo","value":1},
{"from":"Popoloca","to":"Arrocillo Amarillo","value":1},
{"from":"Purhépecha","to":"Arrocillo Amarillo","value":1},
{"from":"Tecuate","to":"Arrocillo Amarillo","value":1},
{"from":"Tepehua","to":"Arrocillo Amarillo","value":1},
{"from":"Tlahuica","to":"Arrocillo Amarillo","value":1},
{"from":"Tlapaneco","to":"Arrocillo Amarillo","value":1},
{"from":"Totonaco","to":"Arrocillo Amarillo","value":1},
{"from":"Triqui","to":"Arrocillo Amarillo","value":1},
{"from":"Zapoteco","to":"Arrocillo Amarillo","value":1},
{"from":"Guarijío","to":"Azul","value":1},
{"from":"Otomí","to":"Azul","value":1},
{"from":"Pima","to":"Azul","value":1},
{"from":"Purhépecha","to":"Azul","value":1},
{"from":"Tarahumara","to":"Azul","value":1},
{"from":"Tepehuano del norte","to":"Azul","value":1},
{"from":"Cora","to":"Blando","value":1},
{"from":"Guarijío","to":"Blando","value":1},
{"from":"Huichol","to":"Blando","value":1},
{"from":"Mayo","to":"Blando","value":1},
{"from":"Nahua","to":"Blando","value":1},
{"from":"Pima","to":"Blando","value":1},
{"from":"Tarahumara","to":"Blando","value":1},
{"from":"Tepehuano del norte","to":"Blando","value":1},
{"from":"Tepehuano del sur","to":"Blando","value":1},
{"from":"Yaqui","to":"Blando","value":1},
{"from":"Cora","to":"Bofo","value":1},
{"from":"Huichol","to":"Bofo","value":1},
{"from":"Nahua","to":"Bofo","value":1},
{"from":"Tarahumara","to":"Bofo","value":1},
{"from":"Tepehuano del norte","to":"Bofo","value":1},
{"from":"Tepehuano del sur","to":"Bofo","value":1},
{"from":"Akateko","to":"Bolita","value":1},
{"from":"Amuzgo","to":"Bolita","value":1},
{"from":"Awakateko","to":"Bolita","value":1},
{"from":"Chatino","to":"Bolita","value":1},
{"from":"Chichimeca","to":"Bolita","value":1},
{"from":"Chinanteco","to":"Bolita","value":1},
{"from":"Chocholteco","to":"Bolita","value":1},
{"from":"Ch'ol","to":"Bolita","value":1},
{"from":"Chontal de Oaxaca","to":"Bolita","value":1},
{"from":"Chuj","to":"Bolita","value":1},
{"from":"Cora","to":"Bolita","value":1},
{"from":"Cuicateco","to":"Bolita","value":1},
{"from":"Huasteco","to":"Bolita","value":1},
{"from":"Huave","to":"Bolita","value":1},
{"from":"Huichol","to":"Bolita","value":1},
{"from":"Ixcateco","to":"Bolita","value":1},
{"from":"Jakalteko","to":"Bolita","value":1},
{"from":"Mame","to":"Bolita","value":1},
{"from":"Matlatzinca","to":"Bolita","value":1},
{"from":"Mazahua","to":"Bolita","value":1},
{"from":"Mazateco","to":"Bolita","value":1},
{"from":"Mixe","to":"Bolita","value":1},
{"from":"Nahua","to":"Bolita","value":1},
{"from":"Oluteco","to":"Bolita","value":1},
{"from":"Otomí","to":"Bolita","value":1},
{"from":"Pame","to":"Bolita","value":1},
{"from":"Pima","to":"Bolita","value":1},
{"from":"Popoloca","to":"Bolita","value":1},
{"from":"Popoluca de la Sierra","to":"Bolita","value":1},
{"from":"Purhépecha","to":"Bolita","value":1},
{"from":"Q'Anjob'Al","to":"Bolita","value":1},
{"from":"Sayulteco","to":"Bolita","value":1},
{"from":"Tarahumara","to":"Bolita","value":1},
{"from":"Tecuate","to":"Bolita","value":1},
{"from":"Teko","to":"Bolita","value":1},
{"from":"Tepehua","to":"Bolita","value":1},
{"from":"Tepehuano del norte","to":"Bolita","value":1},
{"from":"Tepehuano del sur","to":"Bolita","value":1},
{"from":"Texistepequeño","to":"Bolita","value":1},
{"from":"Tlahuica","to":"Bolita","value":1},
{"from":"Tlapaneco","to":"Bolita","value":1},
{"from":"Tojolabal","to":"Bolita","value":1},
{"from":"Totonaco","to":"Bolita","value":1},
{"from":"Triqui","to":"Bolita","value":1},
{"from":"Tseltal","to":"Bolita","value":1},
{"from":"Tzotzil","to":"Bolita","value":1},
{"from":"Zapoteco","to":"Bolita","value":1},
{"from":"Zoque","to":"Bolita","value":1},
{"from":"Matlatzinca","to":"Cacahuacintle","value":1},
{"from":"Mazahua","to":"Cacahuacintle","value":1},
{"from":"Mazateco","to":"Cacahuacintle","value":1},
{"from":"Nahua","to":"Cacahuacintle","value":1},
{"from":"Otomí","to":"Cacahuacintle","value":1},
{"from":"Popoloca","to":"Cacahuacintle","value":1},
{"from":"Purhépecha","to":"Cacahuacintle","value":1},
{"from":"Tlahuica","to":"Cacahuacintle","value":1},
{"from":"Totonaco","to":"Cacahuacintle","value":1},
{"from":"Amuzgo","to":"Celaya","value":1},
{"from":"Ayapaneco","to":"Celaya","value":1},
{"from":"Chatino","to":"Celaya","value":1},
{"from":"Chichimeca","to":"Celaya","value":1},
{"from":"Chinanteco","to":"Celaya","value":1},
{"from":"Chocholteco","to":"Celaya","value":1},
{"from":"Ch'ol","to":"Celaya","value":1},
{"from":"Chontal de Oaxaca","to":"Celaya","value":1},
{"from":"Chontal de Tabasco","to":"Celaya","value":1},
{"from":"Cora","to":"Celaya","value":1},
{"from":"Cuicateco","to":"Celaya","value":1},
{"from":"Guarijío","to":"Celaya","value":1},
{"from":"Huasteco","to":"Celaya","value":1},
{"from":"Huave","to":"Celaya","value":1},
{"from":"Huichol","to":"Celaya","value":1},
{"from":"Ixcateco","to":"Celaya","value":1},
{"from":"Mame","to":"Celaya","value":1},
{"from":"Matlatzinca","to":"Celaya","value":1},
{"from":"Mayo","to":"Celaya","value":1},
{"from":"Mazahua","to":"Celaya","value":1},
{"from":"Mazateco","to":"Celaya","value":1},
{"from":"Mixe","to":"Celaya","value":1},
{"from":"Nahua","to":"Celaya","value":1},
{"from":"Oluteco","to":"Celaya","value":1},
{"from":"Otomí","to":"Celaya","value":1},
{"from":"Pame","to":"Celaya","value":1},
{"from":"Pima","to":"Celaya","value":1},
{"from":"Popoloca","to":"Celaya","value":1},
{"from":"Popoluca de la Sierra","to":"Celaya","value":1},
{"from":"Purhépecha","to":"Celaya","value":1},
{"from":"Sayulteco","to":"Celaya","value":1},
{"from":"Tarahumara","to":"Celaya","value":1},
{"from":"Tecuate","to":"Celaya","value":1},
{"from":"Tepehua","to":"Celaya","value":1},
{"from":"Tepehuano del norte","to":"Celaya","value":1},
{"from":"Tepehuano del sur","to":"Celaya","value":1},
{"from":"Texistepequeño","to":"Celaya","value":1},
{"from":"Tlahuica","to":"Celaya","value":1},
{"from":"Tlapaneco","to":"Celaya","value":1},
{"from":"Totonaco","to":"Celaya","value":1},
{"from":"Triqui","to":"Celaya","value":1},
{"from":"Tseltal","to":"Celaya","value":1},
{"from":"Tzotzil","to":"Celaya","value":1},
{"from":"Zapoteco","to":"Celaya","value":1},
{"from":"Zoque","to":"Celaya","value":1},
{"from":"Amuzgo","to":"Chalqueño","value":1},
{"from":"Chatino","to":"Chalqueño","value":1},
{"from":"Chichimeca","to":"Chalqueño","value":1},
{"from":"Chinanteco","to":"Chalqueño","value":1},
{"from":"Chocholteco","to":"Chalqueño","value":1},
{"from":"Cora","to":"Chalqueño","value":1},
{"from":"Cuicateco","to":"Chalqueño","value":1},
{"from":"Huasteco","to":"Chalqueño","value":1},
{"from":"Huichol","to":"Chalqueño","value":1},
{"from":"Ixcateco","to":"Chalqueño","value":1},
{"from":"Matlatzinca","to":"Chalqueño","value":1},
{"from":"Mazahua","to":"Chalqueño","value":1},
{"from":"Mazateco","to":"Chalqueño","value":1},
{"from":"Mixe","to":"Chalqueño","value":1},
{"from":"Nahua","to":"Chalqueño","value":1},
{"from":"Otomí","to":"Chalqueño","value":1},
{"from":"Pame","to":"Chalqueño","value":1},
{"from":"Popoloca","to":"Chalqueño","value":1},
{"from":"Purhépecha","to":"Chalqueño","value":1},
{"from":"Tecuate","to":"Chalqueño","value":1},
{"from":"Tepehua","to":"Chalqueño","value":1},
{"from":"Tepehuano del sur","to":"Chalqueño","value":1},
{"from":"Tlahuica","to":"Chalqueño","value":1},
{"from":"Tlapaneco","to":"Chalqueño","value":1},
{"from":"Totonaco","to":"Chalqueño","value":1},
{"from":"Triqui","to":"Chalqueño","value":1},
{"from":"Zapoteco","to":"Chalqueño","value":1},
{"from":"Guarijío","to":"Chapalote","value":1},
{"from":"Mayo","to":"Chapalote","value":1},
{"from":"Pima","to":"Chapalote","value":1},
{"from":"Tarahumara","to":"Chapalote","value":1},
{"from":"Tepehuano del norte","to":"Chapalote","value":1},
{"from":"Yaqui","to":"Chapalote","value":1},
{"from":"Akateko","to":"Chiquito","value":1},
{"from":"Awakateko","to":"Chiquito","value":1},
{"from":"Chatino","to":"Chiquito","value":1},
{"from":"Chinanteco","to":"Chiquito","value":1},
{"from":"Chocholteco","to":"Chiquito","value":1},
{"from":"Chontal de Oaxaca","to":"Chiquito","value":1},
{"from":"Cuicateco","to":"Chiquito","value":1},
{"from":"Huave","to":"Chiquito","value":1},
{"from":"Ixcateco","to":"Chiquito","value":1},
{"from":"Jakalteko","to":"Chiquito","value":1},
{"from":"Mame","to":"Chiquito","value":1},
{"from":"Mazateco","to":"Chiquito","value":1},
{"from":"Mixe","to":"Chiquito","value":1},
{"from":"Nahua","to":"Chiquito","value":1},
{"from":"Q'Anjob'Al","to":"Chiquito","value":1},
{"from":"Teko","to":"Chiquito","value":1},
{"from":"Tojolabal","to":"Chiquito","value":1},
{"from":"Triqui","to":"Chiquito","value":1},
{"from":"Tseltal","to":"Chiquito","value":1},
{"from":"Tzotzil","to":"Chiquito","value":1},
{"from":"Zapoteco","to":"Chiquito","value":1},
{"from":"Zoque","to":"Chiquito","value":1},
{"from":"Chinanteco","to":"Choapaneco","value":1},
{"from":"Mixe","to":"Choapaneco","value":1},
{"from":"Zapoteco","to":"Choapaneco","value":1},
{"from":"Akateko","to":"Comiteco","value":1},
{"from":"Awakateko","to":"Comiteco","value":1},
{"from":"Chatino","to":"Comiteco","value":1},
{"from":"Chinanteco","to":"Comiteco","value":1},
{"from":"Chocholteco","to":"Comiteco","value":1},
{"from":"Ch'ol","to":"Comiteco","value":1},
{"from":"Chontal de Oaxaca","to":"Comiteco","value":1},
{"from":"Chontal de Tabasco","to":"Comiteco","value":1},
{"from":"Chuj","to":"Comiteco","value":1},
{"from":"Cuicateco","to":"Comiteco","value":1},
{"from":"Huave","to":"Comiteco","value":1},
{"from":"Ixcateco","to":"Comiteco","value":1},
{"from":"Jakalteko","to":"Comiteco","value":1},
{"from":"K'iche'","to":"Comiteco","value":1},
{"from":"Lacandón","to":"Comiteco","value":1},
{"from":"Mame","to":"Comiteco","value":1},
{"from":"Mazateco","to":"Comiteco","value":1},
{"from":"Mixe","to":"Comiteco","value":1},
{"from":"Nahua","to":"Comiteco","value":1},
{"from":"Q'Anjob'Al","to":"Comiteco","value":1},
{"from":"Teko","to":"Comiteco","value":1},
{"from":"Tojolabal","to":"Comiteco","value":1},
{"from":"Triqui","to":"Comiteco","value":1},
{"from":"Tseltal","to":"Comiteco","value":1},
{"from":"Tzotzil","to":"Comiteco","value":1},
{"from":"Zapoteco","to":"Comiteco","value":1},
{"from":"Zoque","to":"Comiteco","value":1},
{"from":"Sin Pueblos","to":"Complejo Serrano de Jalisco","value":1},
{"from":"Amuzgo","to":"Conejo","value":1},
{"from":"Chatino","to":"Conejo","value":1},
{"from":"Chontal de Oaxaca","to":"Conejo","value":1},
{"from":"Cora","to":"Conejo","value":1},
{"from":"Huichol","to":"Conejo","value":1},
{"from":"Matlatzinca","to":"Conejo","value":1},
{"from":"Mayo","to":"Conejo","value":1},
{"from":"Mazahua","to":"Conejo","value":1},
{"from":"Nahua","to":"Conejo","value":1},
{"from":"Otomí","to":"Conejo","value":1},
{"from":"Purhépecha","to":"Conejo","value":1},
{"from":"Tecuate","to":"Conejo","value":1},
{"from":"Tlapaneco","to":"Conejo","value":1},
{"from":"Triqui","to":"Conejo","value":1},
{"from":"Tseltal","to":"Conejo","value":1},
{"from":"Tzotzil","to":"Conejo","value":1},
{"from":"Zapoteco","to":"Conejo","value":1},
{"from":"Amuzgo","to":"Cónico","value":1},
{"from":"Ayapaneco","to":"Cónico","value":1},
{"from":"Chatino","to":"Cónico","value":1},
{"from":"Chichimeca","to":"Cónico","value":1},
{"from":"Chinanteco","to":"Cónico","value":1},
{"from":"Chocholteco","to":"Cónico","value":1},
{"from":"Ch'ol","to":"Cónico","value":1},
{"from":"Chontal de Oaxaca","to":"Cónico","value":1},
{"from":"Chontal de Tabasco","to":"Cónico","value":1},
{"from":"Cora","to":"Cónico","value":1},
{"from":"Cuicateco","to":"Cónico","value":1},
{"from":"Huasteco","to":"Cónico","value":1},
{"from":"Huave","to":"Cónico","value":1},
{"from":"Huichol","to":"Cónico","value":1},
{"from":"Ixcateco","to":"Cónico","value":1},
{"from":"Matlatzinca","to":"Cónico","value":1},
{"from":"Mazahua","to":"Cónico","value":1},
{"from":"Mazateco","to":"Cónico","value":1},
{"from":"Mixe","to":"Cónico","value":1},
{"from":"Nahua","to":"Cónico","value":1},
{"from":"Oluteco","to":"Cónico","value":1},
{"from":"Otomí","to":"Cónico","value":1},
{"from":"Pame","to":"Cónico","value":1},
{"from":"Popoloca","to":"Cónico","value":1},
{"from":"Popoluca de la Sierra","to":"Cónico","value":1},
{"from":"Purhépecha","to":"Cónico","value":1},
{"from":"Sayulteco","to":"Cónico","value":1},
{"from":"Tarahumara","to":"Cónico","value":1},
{"from":"Tecuate","to":"Cónico","value":1},
{"from":"Tepehua","to":"Cónico","value":1},
{"from":"Tepehuano del norte","to":"Cónico","value":1},
{"from":"Tepehuano del sur","to":"Cónico","value":1},
{"from":"Texistepequeño","to":"Cónico","value":1},
{"from":"Tlahuica","to":"Cónico","value":1},
{"from":"Tlapaneco","to":"Cónico","value":1},
{"from":"Totonaco","to":"Cónico","value":1},
{"from":"Triqui","to":"Cónico","value":1},
{"from":"Tseltal","to":"Cónico","value":1},
{"from":"Tzotzil","to":"Cónico","value":1},
{"from":"Zapoteco","to":"Cónico","value":1},
{"from":"Zoque","to":"Cónico","value":1},
{"from":"Chichimeca","to":"Cónico Norteño","value":1},
{"from":"Cora","to":"Cónico Norteño","value":1},
{"from":"Guarijío","to":"Cónico Norteño","value":1},
{"from":"Huasteco","to":"Cónico Norteño","value":1},
{"from":"Huichol","to":"Cónico Norteño","value":1},
{"from":"Kikapú","to":"Cónico Norteño","value":1},
{"from":"Matlatzinca","to":"Cónico Norteño","value":1},
{"from":"Mayo","to":"Cónico Norteño","value":1},
{"from":"Mazahua","to":"Cónico Norteño","value":1},
{"from":"Mazateco","to":"Cónico Norteño","value":1},
{"from":"Nahua","to":"Cónico Norteño","value":1},
{"from":"Otomí","to":"Cónico Norteño","value":1},
{"from":"Pame","to":"Cónico Norteño","value":1},
{"from":"Pima","to":"Cónico Norteño","value":1},
{"from":"Popoloca","to":"Cónico Norteño","value":1},
{"from":"Purhépecha","to":"Cónico Norteño","value":1},
{"from":"Tarahumara","to":"Cónico Norteño","value":1},
{"from":"Tepehua","to":"Cónico Norteño","value":1},
{"from":"Tepehuano del norte","to":"Cónico Norteño","value":1},
{"from":"Tepehuano del sur","to":"Cónico Norteño","value":1},
{"from":"Tlahuica","to":"Cónico Norteño","value":1},
{"from":"Totonaco","to":"Cónico Norteño","value":1},
{"from":"Chinanteco","to":"Coscomatepec","value":1},
{"from":"Cuicateco","to":"Coscomatepec","value":1},
{"from":"Mazateco","to":"Coscomatepec","value":1},
{"from":"Nahua","to":"Coscomatepec","value":1},
{"from":"Oluteco","to":"Coscomatepec","value":1},
{"from":"Otomí","to":"Coscomatepec","value":1},
{"from":"Popoluca de la Sierra","to":"Coscomatepec","value":1},
{"from":"Sayulteco","to":"Coscomatepec","value":1},
{"from":"Texistepequeño","to":"Coscomatepec","value":1},
{"from":"Totonaco","to":"Coscomatepec","value":1},
{"from":"Guarijío","to":"Cristalino de Chihuahua","value":1},
{"from":"Mayo","to":"Cristalino de Chihuahua","value":1},
{"from":"Pima","to":"Cristalino de Chihuahua","value":1},
{"from":"Tarahumara","to":"Cristalino de Chihuahua","value":1},
{"from":"Tepehuano del norte","to":"Cristalino de Chihuahua","value":1},
{"from":"Akateko","to":"Cubano Amarillo","value":1},
{"from":"Awakateko","to":"Cubano Amarillo","value":1},
{"from":"Ch'ol","to":"Cubano Amarillo","value":1},
{"from":"Chuj","to":"Cubano Amarillo","value":1},
{"from":"Jakalteko","to":"Cubano Amarillo","value":1},
{"from":"K'iche'","to":"Cubano Amarillo","value":1},
{"from":"Lacandón","to":"Cubano Amarillo","value":1},
{"from":"Mame","to":"Cubano Amarillo","value":1},
{"from":"Q'Anjob'Al","to":"Cubano Amarillo","value":1},
{"from":"Teko","to":"Cubano Amarillo","value":1},
{"from":"Tojolabal","to":"Cubano Amarillo","value":1},
{"from":"Tseltal","to":"Cubano Amarillo","value":1},
{"from":"Tzotzil","to":"Cubano Amarillo","value":1},
{"from":"Zoque","to":"Cubano Amarillo","value":1},
{"from":"Cora","to":"Dulce","value":1},
{"from":"Guarijío","to":"Dulce","value":1},
{"from":"Huichol","to":"Dulce","value":1},
{"from":"Mayo","to":"Dulce","value":1},
{"from":"Mazahua","to":"Dulce","value":1},
{"from":"Nahua","to":"Dulce","value":1},
{"from":"Otomí","to":"Dulce","value":1},
{"from":"Pima","to":"Dulce","value":1},
{"from":"Purhépecha","to":"Dulce","value":1},
{"from":"Tarahumara","to":"Dulce","value":1},
{"from":"Tepehuano del norte","to":"Dulce","value":1},
{"from":"Tepehuano del sur","to":"Dulce","value":1},
{"from":"Cora","to":"Dulcillo del Noroeste","value":1},
{"from":"Guarijío","to":"Dulcillo del Noroeste","value":1},
{"from":"Huichol","to":"Dulcillo del Noroeste","value":1},
{"from":"Mayo","to":"Dulcillo del Noroeste","value":1},
{"from":"Nahua","to":"Dulcillo del Noroeste","value":1},
{"from":"Pima","to":"Dulcillo del Noroeste","value":1},
{"from":"Tarahumara","to":"Dulcillo del Noroeste","value":1},
{"from":"Tepehuano del norte","to":"Dulcillo del Noroeste","value":1},
{"from":"Tepehuano del sur","to":"Dulcillo del Noroeste","value":1},
{"from":"Yaqui","to":"Dulcillo del Noroeste","value":1},
{"from":"Akateko","to":"Dzit Bacal","value":1},
{"from":"Awakateko","to":"Dzit Bacal","value":1},
{"from":"Awakateko","to":"Dzit Bacal","value":1},
{"from":"Ch'ol","to":"Dzit Bacal","value":1},
{"from":"Chontal de Tabasco","to":"Dzit Bacal","value":1},
{"from":"Chuj","to":"Dzit Bacal","value":1},
{"from":"Huasteco","to":"Dzit Bacal","value":1},
{"from":"Ixil","to":"Dzit Bacal","value":1},
{"from":"Jakalteko","to":"Dzit Bacal","value":1},
{"from":"Kaqchikel","to":"Dzit Bacal","value":1},
{"from":"K'iche'","to":"Dzit Bacal","value":1},
{"from":"Lacandón","to":"Dzit Bacal","value":1},
{"from":"Mame","to":"Dzit Bacal","value":1},
{"from":"Maya","to":"Dzit Bacal","value":1},
{"from":"Mazateco","to":"Dzit Bacal","value":1},
{"from":"Nahua","to":"Dzit Bacal","value":1},
{"from":"Otomí","to":"Dzit Bacal","value":1},
{"from":"Q'Anjob'Al","to":"Dzit Bacal","value":1},
{"from":"Q'Eqchi'","to":"Dzit Bacal","value":1},
{"from":"Teko","to":"Dzit Bacal","value":1},
{"from":"Tepehua","to":"Dzit Bacal","value":1},
{"from":"Tojolabal","to":"Dzit Bacal","value":1},
{"from":"Totonaco","to":"Dzit Bacal","value":1},
{"from":"Tseltal","to":"Dzit Bacal","value":1},
{"from":"Tzotzil","to":"Dzit Bacal","value":1},
{"from":"Zoque","to":"Dzit Bacal","value":1},
{"from":"Cora","to":"Elotero de Sinaloa","value":1},
{"from":"Huichol","to":"Elotero de Sinaloa","value":1},
{"from":"Nahua","to":"Elotero de Sinaloa","value":1},
{"from":"Purhépecha","to":"Elotero de Sinaloa","value":1},
{"from":"Tepehuano del sur","to":"Elotero de Sinaloa","value":1},
{"from":"Amuzgo","to":"Elotes Cónicos","value":1},
{"from":"Chatino","to":"Elotes Cónicos","value":1},
{"from":"Chichimeca","to":"Elotes Cónicos","value":1},
{"from":"Chinanteco","to":"Elotes Cónicos","value":1},
{"from":"Chocholteco","to":"Elotes Cónicos","value":1},
{"from":"Cuicateco","to":"Elotes Cónicos","value":1},
{"from":"Huasteco","to":"Elotes Cónicos","value":1},
{"from":"Huichol","to":"Elotes Cónicos","value":1},
{"from":"Ixcateco","to":"Elotes Cónicos","value":1},
{"from":"Matlatzinca","to":"Elotes Cónicos","value":1},
{"from":"Mazahua","to":"Elotes Cónicos","value":1},
{"from":"Mazateco","to":"Elotes Cónicos","value":1},
{"from":"Mixe","to":"Elotes Cónicos","value":1},
{"from":"Nahua","to":"Elotes Cónicos","value":1},
{"from":"Otomí","to":"Elotes Cónicos","value":1},
{"from":"Pame","to":"Elotes Cónicos","value":1},
{"from":"Popoloca","to":"Elotes Cónicos","value":1},
{"from":"Purhépecha","to":"Elotes Cónicos","value":1},
{"from":"Tecuate","to":"Elotes Cónicos","value":1},
{"from":"Tepehua","to":"Elotes Cónicos","value":1},
{"from":"Tepehuano del sur","to":"Elotes Cónicos","value":1},
{"from":"Tlahuica","to":"Elotes Cónicos","value":1},
{"from":"Tlapaneco","to":"Elotes Cónicos","value":1},
{"from":"Totonaco","to":"Elotes Cónicos","value":1},
{"from":"Triqui","to":"Elotes Cónicos","value":1},
{"from":"Zapoteco","to":"Elotes Cónicos","value":1},
{"from":"Amuzgo","to":"Elotes Occidentales","value":1},
{"from":"Chatino","to":"Elotes Occidentales","value":1},
{"from":"Chichimeca","to":"Elotes Occidentales","value":1},
{"from":"Chinanteco","to":"Elotes Occidentales","value":1},
{"from":"Chocholteco","to":"Elotes Occidentales","value":1},
{"from":"Cora","to":"Elotes Occidentales","value":1},
{"from":"Cuicateco","to":"Elotes Occidentales","value":1},
{"from":"Huasteco","to":"Elotes Occidentales","value":1},
{"from":"Huichol","to":"Elotes Occidentales","value":1},
{"from":"Ixcateco","to":"Elotes Occidentales","value":1},
{"from":"Matlatzinca","to":"Elotes Occidentales","value":1},
{"from":"Mazahua","to":"Elotes Occidentales","value":1},
{"from":"Mazateco","to":"Elotes Occidentales","value":1},
{"from":"Mixe","to":"Elotes Occidentales","value":1},
{"from":"Nahua","to":"Elotes Occidentales","value":1},
{"from":"Otomí","to":"Elotes Occidentales","value":1},
{"from":"Pame","to":"Elotes Occidentales","value":1},
{"from":"Popoloca","to":"Elotes Occidentales","value":1},
{"from":"Purhépecha","to":"Elotes Occidentales","value":1},
{"from":"Tarahumara","to":"Elotes Occidentales","value":1},
{"from":"Tecuate","to":"Elotes Occidentales","value":1},
{"from":"Tepehua","to":"Elotes Occidentales","value":1},
{"from":"Tepehuano del norte","to":"Elotes Occidentales","value":1},
{"from":"Tepehuano del sur","to":"Elotes Occidentales","value":1},
{"from":"Tlahuica","to":"Elotes Occidentales","value":1},
{"from":"Tlapaneco","to":"Elotes Occidentales","value":1},
{"from":"Totonaco","to":"Elotes Occidentales","value":1},
{"from":"Triqui","to":"Elotes Occidentales","value":1},
{"from":"Zapoteco","to":"Elotes Occidentales","value":1},
{"from":"Cora","to":"Gordo","value":1},
{"from":"Guarijío","to":"Gordo","value":1},
{"from":"Huichol","to":"Gordo","value":1},
{"from":"Mayo","to":"Gordo","value":1},
{"from":"Nahua","to":"Gordo","value":1},
{"from":"Pima","to":"Gordo","value":1},
{"from":"Tarahumara","to":"Gordo","value":1},
{"from":"Tepehuano del norte","to":"Gordo","value":1},
{"from":"Tepehuano del sur","to":"Gordo","value":1},
{"from":"Cora","to":"Harinoso de Ocho","value":1},
{"from":"Huichol","to":"Harinoso de Ocho","value":1},
{"from":"Nahua","to":"Harinoso de Ocho","value":1},
{"from":"Tepehuano del sur","to":"Harinoso de Ocho","value":1},
{"from":"Tepehuano del sur","to":"Jala","value":1},
{"from":"Purhépecha","to":"Jala","value":1},
{"from":"Nahua","to":"Jala","value":1},
{"from":"Huichol","to":"Jala","value":1},
{"from":"Cora","to":"Jala","value":1},
{"from":"Mixe","to":"Mixeño","value":1},
{"from":"Ixcateco","to":"Mixeño","value":1},
{"from":"Chocholteco","to":"Mixeño","value":1},
{"from":"Chinanteco","to":"Mixeño","value":1},
{"from":"Chinanteco","to":"Mixteco","value":1},
{"from":"Mixteco","to":"Mixteco","value":1},
{"from":"Zapoteco","to":"Mixteco","value":1},
{"from":"Mame","to":"Motozinteco","value":1},
{"from":"Tseltal","to":"Motozinteco","value":1},
{"from":"Tzotzil","to":"Motozinteco","value":1},
{"from":"Mame","to":"Mountain Yellow","value":1},
{"from":"Purhépecha","to":"Mountain Yellow","value":1},
{"from":"Amuzgo","to":"Mushito","value":1},
{"from":"Chatino","to":"Mushito","value":1},
{"from":"Chichimeca","to":"Mushito","value":1},
{"from":"Chinanteco","to":"Mushito","value":1},
{"from":"Chocholteco","to":"Mushito","value":1},
{"from":"Cora","to":"Mushito","value":1},
{"from":"Cuicateco","to":"Mushito","value":1},
{"from":"Huasteco","to":"Mushito","value":1},
{"from":"Huichol","to":"Mushito","value":1},
{"from":"Ixcateco","to":"Mushito","value":1},
{"from":"Matlatzinca","to":"Mushito","value":1},
{"from":"Mazahua","to":"Mushito","value":1},
{"from":"Mazateco","to":"Mushito","value":1},
{"from":"Nahua","to":"Mushito","value":1},
{"from":"Otomí","to":"Mushito","value":1},
{"from":"Pame","to":"Mushito","value":1},
{"from":"Popoloca","to":"Mushito","value":1},
{"from":"Purhépecha","to":"Mushito","value":1},
{"from":"Tecuate","to":"Mushito","value":1},
{"from":"Tepehua","to":"Mushito","value":1},
{"from":"Tlahuica","to":"Mushito","value":1},
{"from":"Tlapaneco","to":"Mushito","value":1},
{"from":"Totonaco","to":"Mushito","value":1},
{"from":"Triqui","to":"Mushito","value":1},
{"from":"Zapoteco","to":"Mushito","value":1},
{"from":"Purhépecha","to":"Mushito de Michoacán","value":1},
{"from":"Akateko","to":"Nal-tel","value":1},
{"from":"Amuzgo","to":"Nal-tel","value":1},
{"from":"Awakateko","to":"Nal-tel","value":1},
{"from":"Chatino","to":"Nal-tel","value":1},
{"from":"Chinanteco","to":"Nal-tel","value":1},
{"from":"Chocholteco","to":"Nal-tel","value":1},
{"from":"Ch'ol","to":"Nal-tel","value":1},
{"from":"Chontal de Oaxaca","to":"Nal-tel","value":1},
{"from":"Chuj","to":"Nal-tel","value":1},
{"from":"Chuj","to":"Nal-tel","value":1},
{"from":"Cuicateco","to":"Nal-tel","value":1},
{"from":"Huasteco","to":"Nal-tel","value":1},
{"from":"Huave","to":"Nal-tel","value":1},
{"from":"Ixcateco","to":"Nal-tel","value":1},
{"from":"Ixil","to":"Nal-tel","value":1},
{"from":"Jakalteko","to":"Nal-tel","value":1},
{"from":"Kaqchikel","to":"Nal-tel","value":1},
{"from":"K'iche'","to":"Nal-tel","value":1},
{"from":"K'iche'","to":"Nal-tel","value":1},
{"from":"Lacandón","to":"Nal-tel","value":1},
{"from":"Mame","to":"Nal-tel","value":1},
{"from":"Maya","to":"Nal-tel","value":1},
{"from":"Mazateco","to":"Nal-tel","value":1},
{"from":"Mixe","to":"Nal-tel","value":1},
{"from":"Nahua","to":"Nal-tel","value":1},
{"from":"Nahua","to":"Nal-tel","value":1},
{"from":"Otomí","to":"Nal-tel","value":1},
{"from":"Popoloca","to":"Nal-tel","value":1},
{"from":"Q'Anjob'Al","to":"Nal-tel","value":1},
{"from":"Q'Eqchi'","to":"Nal-tel","value":1},
{"from":"Tecuate","to":"Nal-tel","value":1},
{"from":"Teko","to":"Nal-tel","value":1},
{"from":"Tepehua","to":"Nal-tel","value":1},
{"from":"Tlapaneco","to":"Nal-tel","value":1},
{"from":"Tojolabal","to":"Nal-tel","value":1},
{"from":"Totonaco","to":"Nal-tel","value":1},
{"from":"Triqui","to":"Nal-tel","value":1},
{"from":"Tseltal","to":"Nal-tel","value":1},
{"from":"Tzotzil","to":"Nal-tel","value":1},
{"from":"Zapoteco","to":"Nal-tel","value":1},
{"from":"Zoque","to":"Nal-tel","value":1},
{"from":"Akateko","to":"Nal-tel de Altura","value":1},
{"from":"Amuzgo","to":"Nal-tel de Altura","value":1},
{"from":"Awakateko","to":"Nal-tel de Altura","value":1},
{"from":"Chatino","to":"Nal-tel de Altura","value":1},
{"from":"Chinanteco","to":"Nal-tel de Altura","value":1},
{"from":"Chocholteco","to":"Nal-tel de Altura","value":1},
{"from":"Ch'ol","to":"Nal-tel de Altura","value":1},
{"from":"Chontal de Oaxaca","to":"Nal-tel de Altura","value":1},
{"from":"Chuj","to":"Nal-tel de Altura","value":1},
{"from":"Cuicateco","to":"Nal-tel de Altura","value":1},
{"from":"Ixcateco","to":"Nal-tel de Altura","value":1},
{"from":"Jakalteko","to":"Nal-tel de Altura","value":1},
{"from":"K'iche'","to":"Nal-tel de Altura","value":1},
{"from":"Lacandón","to":"Nal-tel de Altura","value":1},
{"from":"Mame","to":"Nal-tel de Altura","value":1},
{"from":"Mazateco","to":"Nal-tel de Altura","value":1},
{"from":"Mixe","to":"Nal-tel de Altura","value":1},
{"from":"Nahua","to":"Nal-tel de Altura","value":1},
{"from":"Popoloca","to":"Nal-tel de Altura","value":1},
{"from":"Q'Anjob'Al","to":"Nal-tel de Altura","value":1},
{"from":"Tecuate","to":"Nal-tel de Altura","value":1},
{"from":"Teko","to":"Nal-tel de Altura","value":1},
{"from":"Tojolabal","to":"Nal-tel de Altura","value":1},
{"from":"Triqui","to":"Nal-tel de Altura","value":1},
{"from":"Tseltal","to":"Nal-tel de Altura","value":1},
{"from":"Tzotzil","to":"Nal-tel de Altura","value":1},
{"from":"Zapoteco","to":"Nal-tel de Altura","value":1},
{"from":"Amuzgo","to":"Negrito","value":1},
{"from":"Chatino","to":"Negrito","value":1},
{"from":"Chinanteco","to":"Negrito","value":1},
{"from":"Chocholteco","to":"Negrito","value":1},
{"from":"Cuicateco","to":"Negrito","value":1},
{"from":"Huasteco","to":"Negrito","value":1},
{"from":"Ixcateco","to":"Negrito","value":1},
{"from":"Nahua","to":"Negrito","value":1},
{"from":"Otomí","to":"Negrito","value":1},
{"from":"Tecuate","to":"Negrito","value":1},
{"from":"Tepehua","to":"Negrito","value":1},
{"from":"Totonaco","to":"Negrito","value":1},
{"from":"Triqui","to":"Negrito","value":1},
{"from":"Zapoteco","to":"Negrito","value":1},
{"from":"Tseltal","to":"Negro de Chimaltenango","value":1},
{"from":"Tzotzil","to":"Negro de Chimaltenango","value":1},
{"from":"Akateko","to":"Olotillo","value":1},
{"from":"Amuzgo","to":"Olotillo","value":1},
{"from":"Awakateko","to":"Olotillo","value":1},
{"from":"Ayapaneco","to":"Olotillo","value":1},
{"from":"Chatino","to":"Olotillo","value":1},
{"from":"Chichimeca","to":"Olotillo","value":1},
{"from":"Chinanteco","to":"Olotillo","value":1},
{"from":"Chocholteco","to":"Olotillo","value":1},
{"from":"Ch'ol","to":"Olotillo","value":1},
{"from":"Chontal de Oaxaca","to":"Olotillo","value":1},
{"from":"Chontal de Tabasco","to":"Olotillo","value":1},
{"from":"Chuj","to":"Olotillo","value":1},
{"from":"Cora","to":"Olotillo","value":1},
{"from":"Cuicateco","to":"Olotillo","value":1},
{"from":"Huasteco","to":"Olotillo","value":1},
{"from":"Huave","to":"Olotillo","value":1},
{"from":"Huichol","to":"Olotillo","value":1},
{"from":"Ixcateco","to":"Olotillo","value":1},
{"from":"Ixil","to":"Olotillo","value":1},
{"from":"Jakalteko","to":"Olotillo","value":1},
{"from":"Kaqchikel","to":"Olotillo","value":1},
{"from":"K'iche'","to":"Olotillo","value":1},
{"from":"Lacandón","to":"Olotillo","value":1},
{"from":"Mame","to":"Olotillo","value":1},
{"from":"Matlatzinca","to":"Olotillo","value":1},
{"from":"Maya","to":"Olotillo","value":1},
{"from":"Mazahua","to":"Olotillo","value":1},
{"from":"Mazateco","to":"Olotillo","value":1},
{"from":"Mixe","to":"Olotillo","value":1},
{"from":"Nahua","to":"Olotillo","value":1},
{"from":"Oluteco","to":"Olotillo","value":1},
{"from":"Otomí","to":"Olotillo","value":1},
{"from":"Pame","to":"Olotillo","value":1},
{"from":"Popoloca","to":"Olotillo","value":1},
{"from":"Popoluca de la Sierra","to":"Olotillo","value":1},
{"from":"Purhépecha","to":"Olotillo","value":1},
{"from":"Q'Anjob'Al","to":"Olotillo","value":1},
{"from":"Q'Eqchi'","to":"Olotillo","value":1},
{"from":"Sayulteco","to":"Olotillo","value":1},
{"from":"Tecuate","to":"Olotillo","value":1},
{"from":"Teko","to":"Olotillo","value":1},
{"from":"Tepehua","to":"Olotillo","value":1},
{"from":"Tepehuano del sur","to":"Olotillo","value":1},
{"from":"Texistepequeño","to":"Olotillo","value":1},
{"from":"Tlahuica","to":"Olotillo","value":1},
{"from":"Tlapaneco","to":"Olotillo","value":1},
{"from":"Tojolabal","to":"Olotillo","value":1},
{"from":"Totonaco","to":"Olotillo","value":1},
{"from":"Triqui","to":"Olotillo","value":1},
{"from":"Tseltal","to":"Olotillo","value":1},
{"from":"Tzotzil","to":"Olotillo","value":1},
{"from":"Zapoteco","to":"Olotillo","value":1},
{"from":"Zoque","to":"Olotillo","value":1},
{"from":"Akateko","to":"Olotón","value":1},
{"from":"Amuzgo","to":"Olotón","value":1},
{"from":"Awakateko","to":"Olotón","value":1},
{"from":"Ayapaneco","to":"Olotón","value":1},
{"from":"Chatino","to":"Olotón","value":1},
{"from":"Chinanteco","to":"Olotón","value":1},
{"from":"Chocholteco","to":"Olotón","value":1},
{"from":"Ch'ol","to":"Olotón","value":1},
{"from":"Chontal de Oaxaca","to":"Olotón","value":1},
{"from":"Chontal de Tabasco","to":"Olotón","value":1},
{"from":"Chuj","to":"Olotón","value":1},
{"from":"Cuicateco","to":"Olotón","value":1},
{"from":"Huasteco","to":"Olotón","value":1},
{"from":"Huave","to":"Olotón","value":1},
{"from":"Ixcateco","to":"Olotón","value":1},
{"from":"Jakalteko","to":"Olotón","value":1},
{"from":"Kaqchikel","to":"Olotón","value":1},
{"from":"K'iche'","to":"Olotón","value":1},
{"from":"Lacandón","to":"Olotón","value":1},
{"from":"Mame","to":"Olotón","value":1},
{"from":"Maya","to":"Olotón","value":1},
{"from":"Mazateco","to":"Olotón","value":1},
{"from":"Mixe","to":"Olotón","value":1},
{"from":"Nahua","to":"Olotón","value":1},
{"from":"Oluteco","to":"Olotón","value":1},
{"from":"Otomí","to":"Olotón","value":1},
{"from":"Popoloca","to":"Olotón","value":1},
{"from":"Popoluca de la Sierra","to":"Olotón","value":1},
{"from":"Q'Anjob'Al","to":"Olotón","value":1},
{"from":"Q'Eqchi'","to":"Olotón","value":1},
{"from":"Sayulteco","to":"Olotón","value":1},
{"from":"Tecuate","to":"Olotón","value":1},
{"from":"Teko","to":"Olotón","value":1},
{"from":"Tepehua","to":"Olotón","value":1},
{"from":"Texistepequeño","to":"Olotón","value":1},
{"from":"Tlahuica","to":"Olotón","value":1},
{"from":"Tlapaneco","to":"Olotón","value":1},
{"from":"Tojolabal","to":"Olotón","value":1},
{"from":"Totonaco","to":"Olotón","value":1},
{"from":"Triqui","to":"Olotón","value":1},
{"from":"Tseltal","to":"Olotón","value":1},
{"from":"Tzotzil","to":"Olotón","value":1},
{"from":"Zapoteco","to":"Olotón","value":1},
{"from":"Zoque","to":"Olotón","value":1},
{"from":"Cora","to":"Onaveño","value":1},
{"from":"Guarijío","to":"Onaveño","value":1},
{"from":"Huichol","to":"Onaveño","value":1},
{"from":"Mayo","to":"Onaveño","value":1},
{"from":"Nahua","to":"Onaveño","value":1},
{"from":"Pima","to":"Onaveño","value":1},
{"from":"Purhépecha","to":"Onaveño","value":1},
{"from":"Tarahumara","to":"Onaveño","value":1},
{"from":"Tepehuano del norte","to":"Onaveño","value":1},
{"from":"Tepehuano del sur","to":"Onaveño","value":1},
{"from":"Tlapaneco","to":"Onaveño","value":1},
{"from":"Yaqui","to":"Onaveño","value":1},
{"from":"Guarijío","to":"Palomero de Chihuahua","value":1},
{"from":"Pima","to":"Palomero de Chihuahua","value":1},
{"from":"Tarahumara","to":"Palomero de Chihuahua","value":1},
{"from":"Tepehuano del norte","to":"Palomero de Chihuahua","value":1},
{"from":"Sin Pueblos","to":"Palomero de Jalisco","value":1},
{"from":"Matlatzinca","to":"Palomero Toluqueño","value":1},
{"from":"Mazahua","to":"Palomero Toluqueño","value":1},
{"from":"Nahua","to":"Palomero Toluqueño","value":1},
{"from":"Otomí","to":"Palomero Toluqueño","value":1},
{"from":"Popoloca","to":"Palomero Toluqueño","value":1},
{"from":"Tlahuica","to":"Palomero Toluqueño","value":1},
{"from":"Totonaco","to":"Palomero Toluqueño","value":1},
{"from":"Amuzgo","to":"Pepitilla","value":1},
{"from":"Chatino","to":"Pepitilla","value":1},
{"from":"Chichimeca","to":"Pepitilla","value":1},
{"from":"Chinanteco","to":"Pepitilla","value":1},
{"from":"Chocholteco","to":"Pepitilla","value":1},
{"from":"Cora","to":"Pepitilla","value":1},
{"from":"Cuicateco","to":"Pepitilla","value":1},
{"from":"Huichol","to":"Pepitilla","value":1},
{"from":"Ixcateco","to":"Pepitilla","value":1},
{"from":"Matlatzinca","to":"Pepitilla","value":1},
{"from":"Mazahua","to":"Pepitilla","value":1},
{"from":"Mazateco","to":"Pepitilla","value":1},
{"from":"Mixe","to":"Pepitilla","value":1},
{"from":"Nahua","to":"Pepitilla","value":1},
{"from":"Otomí","to":"Pepitilla","value":1},
{"from":"Popoloca","to":"Pepitilla","value":1},
{"from":"Purhépecha","to":"Pepitilla","value":1},
{"from":"Tecuate","to":"Pepitilla","value":1},
{"from":"Tepehuano del sur","to":"Pepitilla","value":1},
{"from":"Tlahuica","to":"Pepitilla","value":1},
{"from":"Tlapaneco","to":"Pepitilla","value":1},
{"from":"Triqui","to":"Pepitilla","value":1},
{"from":"Zapoteco","to":"Pepitilla","value":1},
{"from":"Tseltal","to":"Quicheño","value":1},
{"from":"Tzotzil","to":"Quicheño","value":1},
{"from":"Chichimeca","to":"Ratón","value":1},
{"from":"Chinanteco","to":"Ratón","value":1},
{"from":"Cora","to":"Ratón","value":1},
{"from":"Guarijío","to":"Ratón","value":1},
{"from":"Huasteco","to":"Ratón","value":1},
{"from":"Huichol","to":"Ratón","value":1},
{"from":"Kikapú","to":"Ratón","value":1},
{"from":"Matlatzinca","to":"Ratón","value":1},
{"from":"Mazahua","to":"Ratón","value":1},
{"from":"Mazateco","to":"Ratón","value":1},
{"from":"Nahua","to":"Ratón","value":1},
{"from":"Oluteco","to":"Ratón","value":1},
{"from":"Otomí","to":"Ratón","value":1},
{"from":"Pame","to":"Ratón","value":1},
{"from":"Pima","to":"Ratón","value":1},
{"from":"Popoloca","to":"Ratón","value":1},
{"from":"Popoluca de la Sierra","to":"Ratón","value":1},
{"from":"Purhépecha","to":"Ratón","value":1},
{"from":"Sayulteco","to":"Ratón","value":1},
{"from":"Tarahumara","to":"Ratón","value":1},
{"from":"Tepehua","to":"Ratón","value":1},
{"from":"Tepehuano del norte","to":"Ratón","value":1},
{"from":"Tepehuano del sur","to":"Ratón","value":1},
{"from":"Texistepequeño","to":"Ratón","value":1},
{"from":"Tlahuica","to":"Ratón","value":1},
{"from":"Tlapaneco","to":"Ratón","value":1},
{"from":"Totonaco","to":"Ratón","value":1},
{"from":"Cora","to":"Reventador","value":1},
{"from":"Guarijío","to":"Reventador","value":1},
{"from":"Huichol","to":"Reventador","value":1},
{"from":"Mayo","to":"Reventador","value":1},
{"from":"Nahua","to":"Reventador","value":1},
{"from":"Pima","to":"Reventador","value":1},
{"from":"Purhépecha","to":"Reventador","value":1},
{"from":"Tarahumara","to":"Reventador","value":1},
{"from":"Tepehuano del norte","to":"Reventador","value":1},
{"from":"Tepehuano del sur","to":"Reventador","value":1},
{"from":"Chinanteco","to":"Serrano","value":1},
{"from":"Cuicateco","to":"Serrano","value":1},
{"from":"Mazateco","to":"Serrano","value":1},
{"from":"Zapoteco","to":"Serrano","value":1},
{"from":"Amuzgo","to":"Serrano Mixe","value":1},
{"from":"Chatino","to":"Serrano Mixe","value":1},
{"from":"Chinanteco","to":"Serrano Mixe","value":1},
{"from":"Chocholteco","to":"Serrano Mixe","value":1},
{"from":"Cuicateco","to":"Serrano Mixe","value":1},
{"from":"Ixcateco","to":"Serrano Mixe","value":1},
{"from":"Mixe","to":"Serrano Mixe","value":1},
{"from":"Nahua","to":"Serrano Mixe","value":1},
{"from":"Tecuate","to":"Serrano Mixe","value":1},
{"from":"Tlapaneco","to":"Serrano Mixe","value":1},
{"from":"Triqui","to":"Serrano Mixe","value":1},
{"from":"Zapoteco","to":"Serrano Mixe","value":1},
{"from":"Cora","to":"Tablilla de Ocho","value":1},
{"from":"Huichol","to":"Tablilla de Ocho","value":1},
{"from":"Nahua","to":"Tablilla de Ocho","value":1},
{"from":"Otomí","to":"Tablilla de Ocho","value":1},
{"from":"Tepehuano del sur","to":"Tablilla de Ocho","value":1},
{"from":"Amuzgo","to":"Tabloncillo","value":1},
{"from":"Chichimeca","to":"Tabloncillo","value":1},
{"from":"Cora","to":"Tabloncillo","value":1},
{"from":"Guarijío","to":"Tabloncillo","value":1},
{"from":"Huasteco","to":"Tabloncillo","value":1},
{"from":"Huichol","to":"Tabloncillo","value":1},
{"from":"Matlatzinca","to":"Tabloncillo","value":1},
{"from":"Mayo","to":"Tabloncillo","value":1},
{"from":"Mazahua","to":"Tabloncillo","value":1},
{"from":"Mazateco","to":"Tabloncillo","value":1},
{"from":"Nahua","to":"Tabloncillo","value":1},
{"from":"Otomí","to":"Tabloncillo","value":1},
{"from":"Pame","to":"Tabloncillo","value":1},
{"from":"Pima","to":"Tabloncillo","value":1},
{"from":"Popoloca","to":"Tabloncillo","value":1},
{"from":"Purhépecha","to":"Tabloncillo","value":1},
{"from":"Seri","to":"Tabloncillo","value":1},
{"from":"Tarahumara","to":"Tabloncillo","value":1},
{"from":"Tepehua","to":"Tabloncillo","value":1},
{"from":"Tepehuano del norte","to":"Tabloncillo","value":1},
{"from":"Tepehuano del sur","to":"Tabloncillo","value":1},
{"from":"Tlahuica","to":"Tabloncillo","value":1},
{"from":"Tlapaneco","to":"Tabloncillo","value":1},
{"from":"Totonaco","to":"Tabloncillo","value":1},
{"from":"Triqui","to":"Tabloncillo","value":1},
{"from":"Tseltal","to":"Tabloncillo","value":1},
{"from":"Tzotzil","to":"Tabloncillo","value":1},
{"from":"Yaqui","to":"Tabloncillo","value":1},
{"from":"Zoque","to":"Tabloncillo","value":1},
{"from":"Cora","to":"Tabloncillo Perla","value":1},
{"from":"Guarijío","to":"Tabloncillo Perla","value":1},
{"from":"Huichol","to":"Tabloncillo Perla","value":1},
{"from":"Mayo","to":"Tabloncillo Perla","value":1},
{"from":"Nahua","to":"Tabloncillo Perla","value":1},
{"from":"Pima","to":"Tabloncillo Perla","value":1},
{"from":"Purhépecha","to":"Tabloncillo Perla","value":1},
{"from":"Tarahumara","to":"Tabloncillo Perla","value":1},
{"from":"Tepehuano del norte","to":"Tabloncillo Perla","value":1},
{"from":"Tepehuano del sur","to":"Tabloncillo Perla","value":1},
{"from":"Yaqui","to":"Tabloncillo Perla","value":1},
{"from":"Akateko","to":"Tehua","value":1},
{"from":"Awakateko","to":"Tehua","value":1},
{"from":"Ch'ol","to":"Tehua","value":1},
{"from":"Chontal de Tabasco","to":"Tehua","value":1},
{"from":"Chuj","to":"Tehua","value":1},
{"from":"Jakalteko","to":"Tehua","value":1},
{"from":"Lacandón","to":"Tehua","value":1},
{"from":"Mame","to":"Tehua","value":1},
{"from":"Q'Anjob'Al","to":"Tehua","value":1},
{"from":"Teko","to":"Tehua","value":1},
{"from":"Tojolabal","to":"Tehua","value":1},
{"from":"Tseltal","to":"Tehua","value":1},
{"from":"Tzotzil","to":"Tehua","value":1},
{"from":"Zoque","to":"Tehua","value":1},
{"from":"Akateko","to":"Tepecintle","value":1},
{"from":"Amuzgo","to":"Tepecintle","value":1},
{"from":"Awakateko","to":"Tepecintle","value":1},
{"from":"Ayapaneco","to":"Tepecintle","value":1},
{"from":"Chatino","to":"Tepecintle","value":1},
{"from":"Chinanteco","to":"Tepecintle","value":1},
{"from":"Chocholteco","to":"Tepecintle","value":1},
{"from":"Ch'ol","to":"Tepecintle","value":1},
{"from":"Chontal de Oaxaca","to":"Tepecintle","value":1},
{"from":"Chontal de Tabasco","to":"Tepecintle","value":1},
{"from":"Chuj","to":"Tepecintle","value":1},
{"from":"Cuicateco","to":"Tepecintle","value":1},
{"from":"Huasteco","to":"Tepecintle","value":1},
{"from":"Huave","to":"Tepecintle","value":1},
{"from":"Ixcateco","to":"Tepecintle","value":1},
{"from":"Ixil","to":"Tepecintle","value":1},
{"from":"Jakalteko","to":"Tepecintle","value":1},
{"from":"Kaqchikel","to":"Tepecintle","value":1},
{"from":"K'iche'","to":"Tepecintle","value":1},
{"from":"Lacandón","to":"Tepecintle","value":1},
{"from":"Mame","to":"Tepecintle","value":1},
{"from":"Maya","to":"Tepecintle","value":1},
{"from":"Mazateco","to":"Tepecintle","value":1},
{"from":"Mixe","to":"Tepecintle","value":1},
{"from":"Nahua","to":"Tepecintle","value":1},
{"from":"Oluteco","to":"Tepecintle","value":1},
{"from":"Otomí","to":"Tepecintle","value":1},
{"from":"Pame","to":"Tepecintle","value":1},
{"from":"Popoloca","to":"Tepecintle","value":1},
{"from":"Popoluca de la Sierra","to":"Tepecintle","value":1},
{"from":"Q'Anjob'Al","to":"Tepecintle","value":1},
{"from":"Q'Eqchi'","to":"Tepecintle","value":1},
{"from":"Sayulteco","to":"Tepecintle","value":1},
{"from":"Tecuate","to":"Tepecintle","value":1},
{"from":"Teko","to":"Tepecintle","value":1},
{"from":"Tepehua","to":"Tepecintle","value":1},
{"from":"Texistepequeño","to":"Tepecintle","value":1},
{"from":"Tlapaneco","to":"Tepecintle","value":1},
{"from":"Tojolabal","to":"Tepecintle","value":1},
{"from":"Totonaco","to":"Tepecintle","value":1},
{"from":"Triqui","to":"Tepecintle","value":1},
{"from":"Tseltal","to":"Tepecintle","value":1},
{"from":"Tzotzil","to":"Tepecintle","value":1},
{"from":"Zapoteco","to":"Tepecintle","value":1},
{"from":"Zoque","to":"Tepecintle","value":1},
{"from":"Akateko","to":"Tuxpeño","value":1},
{"from":"Amuzgo","to":"Tuxpeño","value":1},
{"from":"Awakateko","to":"Tuxpeño","value":1},
{"from":"Ayapaneco","to":"Tuxpeño","value":1},
{"from":"Ch'ol","to":"Tuxpeño","value":1},
{"from":"Chatino","to":"Tuxpeño","value":1},
{"from":"Chichimeca","to":"Tuxpeño","value":1},
{"from":"Chinanteco","to":"Tuxpeño","value":1},
{"from":"Chocholteco","to":"Tuxpeño","value":1},
{"from":"Chontal de Oaxaca","to":"Tuxpeño","value":1},
{"from":"Chontal de Tabasco","to":"Tuxpeño","value":1},
{"from":"Chuj","to":"Tuxpeño","value":1},
{"from":"Cora","to":"Tuxpeño","value":1},
{"from":"Cuicateco","to":"Tuxpeño","value":1},
{"from":"Guarijío","to":"Tuxpeño","value":1},
{"from":"Huasteco","to":"Tuxpeño","value":1},
{"from":"Huave","to":"Tuxpeño","value":1},
{"from":"Huichol","to":"Tuxpeño","value":1},
{"from":"Ixcateco","to":"Tuxpeño","value":1},
{"from":"Ixil","to":"Tuxpeño","value":1},
{"from":"Jakalteko","to":"Tuxpeño","value":1},
{"from":"K'iche'","to":"Tuxpeño","value":1},
{"from":"Kaqchikel","to":"Tuxpeño","value":1},
{"from":"Kikapú","to":"Tuxpeño","value":1},
{"from":"Lacandón","to":"Tuxpeño","value":1},
{"from":"Mame","to":"Tuxpeño","value":1},
{"from":"Matlatzinca","to":"Tuxpeño","value":1},
{"from":"Maya","to":"Tuxpeño","value":1},
{"from":"Mayo","to":"Tuxpeño","value":1},
{"from":"Mazahua","to":"Tuxpeño","value":1},
{"from":"Mazateco","to":"Tuxpeño","value":1},
{"from":"Mixe","to":"Tuxpeño","value":1},
{"from":"Nahua","to":"Tuxpeño","value":1},
{"from":"Oluteco","to":"Tuxpeño","value":1},
{"from":"Otomí","to":"Tuxpeño","value":1},
{"from":"Pame","to":"Tuxpeño","value":1},
{"from":"Pima","to":"Tuxpeño","value":1},
{"from":"Popoloca","to":"Tuxpeño","value":1},
{"from":"Popoluca de la Sierra","to":"Tuxpeño","value":1},
{"from":"Purhépecha","to":"Tuxpeño","value":1},
{"from":"Q'Anjob'Al","to":"Tuxpeño","value":1},
{"from":"Q'Eqchi'","to":"Tuxpeño","value":1},
{"from":"Sayulteco","to":"Tuxpeño","value":1},
{"from":"Tarahumara","to":"Tuxpeño","value":1},
{"from":"Tecuate","to":"Tuxpeño","value":1},
{"from":"Teko","to":"Tuxpeño","value":1},
{"from":"Tepehua","to":"Tuxpeño","value":1},
{"from":"Tepehuano del norte","to":"Tuxpeño","value":1},
{"from":"Tepehuano del sur","to":"Tuxpeño","value":1},
{"from":"Texistepequeño","to":"Tuxpeño","value":1},
{"from":"Tlahuica","to":"Tuxpeño","value":1},
{"from":"Tlapaneco","to":"Tuxpeño","value":1},
{"from":"Tojolabal","to":"Tuxpeño","value":1},
{"from":"Totonaco","to":"Tuxpeño","value":1},
{"from":"Triqui","to":"Tuxpeño","value":1},
{"from":"Tseltal","to":"Tuxpeño","value":1},
{"from":"Tzotzil","to":"Tuxpeño","value":1},
{"from":"Zapoteco","to":"Tuxpeño","value":1},
{"from":"Zoque","to":"Tuxpeño","value":1},
{"from":"Amuzgo","to":"Tuxpeño Norteño","value":1},
{"from":"Chichimeca","to":"Tuxpeño Norteño","value":1},
{"from":"Cora","to":"Tuxpeño Norteño","value":1},
{"from":"Guarijío","to":"Tuxpeño Norteño","value":1},
{"from":"Huasteco","to":"Tuxpeño Norteño","value":1},
{"from":"Huichol","to":"Tuxpeño Norteño","value":1},
{"from":"Kikapú","to":"Tuxpeño Norteño","value":1},
{"from":"Matlatzinca","to":"Tuxpeño Norteño","value":1},
{"from":"Mayo","to":"Tuxpeño Norteño","value":1},
{"from":"Mazahua","to":"Tuxpeño Norteño","value":1},
{"from":"Nahua","to":"Tuxpeño Norteño","value":1},
{"from":"Otomí","to":"Tuxpeño Norteño","value":1},
{"from":"Pame","to":"Tuxpeño Norteño","value":1},
{"from":"Pima","to":"Tuxpeño Norteño","value":1},
{"from":"Popoloca","to":"Tuxpeño Norteño","value":1},
{"from":"Purhépecha","to":"Tuxpeño Norteño","value":1},
{"from":"Tarahumara","to":"Tuxpeño Norteño","value":1},
{"from":"Tepehua","to":"Tuxpeño Norteño","value":1},
{"from":"Tepehuano del norte","to":"Tuxpeño Norteño","value":1},
{"from":"Tepehuano del sur","to":"Tuxpeño Norteño","value":1},
{"from":"Tlahuica","to":"Tuxpeño Norteño","value":1},
{"from":"Tlapaneco","to":"Tuxpeño Norteño","value":1},
{"from":"Totonaco","to":"Tuxpeño Norteño","value":1},
{"from":"Yaqui","to":"Tuxpeño Norteño","value":1},
{"from":"Sin Pueblos","to":"Urapeño","value":1},
{"from":"Akateko","to":"Vandeño","value":1},
{"from":"Amuzgo","to":"Vandeño","value":1},
{"from":"Awakateko","to":"Vandeño","value":1},
{"from":"Ayapaneco","to":"Vandeño","value":1},
{"from":"Ch'ol","to":"Vandeño","value":1},
{"from":"Chatino","to":"Vandeño","value":1},
{"from":"Chinanteco","to":"Vandeño","value":1},
{"from":"Chocholteco","to":"Vandeño","value":1},
{"from":"Chontal de Oaxaca","to":"Vandeño","value":1},
{"from":"Chontal de Tabasco","to":"Vandeño","value":1},
{"from":"Chuj","to":"Vandeño","value":1},
{"from":"Cora","to":"Vandeño","value":1},
{"from":"Cuicateco","to":"Vandeño","value":1},
{"from":"Guarijío","to":"Vandeño","value":1},
{"from":"Huasteco","to":"Vandeño","value":1},
{"from":"Huave","to":"Vandeño","value":1},
{"from":"Huichol","to":"Vandeño","value":1},
{"from":"Ixcateco","to":"Vandeño","value":1},
{"from":"Ixil","to":"Vandeño","value":1},
{"from":"Jakalteko","to":"Vandeño","value":1},
{"from":"K'iche'","to":"Vandeño","value":1},
{"from":"Kaqchikel","to":"Vandeño","value":1},
{"from":"Lacandón","to":"Vandeño","value":1},
{"from":"Mame","to":"Vandeño","value":1},
{"from":"Matlatzinca","to":"Vandeño","value":1},
{"from":"Maya","to":"Vandeño","value":1},
{"from":"Mayo","to":"Vandeño","value":1},
{"from":"Mazahua","to":"Vandeño","value":1},
{"from":"Mazateco","to":"Vandeño","value":1},
{"from":"Mixe","to":"Vandeño","value":1},
{"from":"Nahua","to":"Vandeño","value":1},
{"from":"Oluteco","to":"Vandeño","value":1},
{"from":"Otomí","to":"Vandeño","value":1},
{"from":"Pame","to":"Vandeño","value":1},
{"from":"Pima","to":"Vandeño","value":1},
{"from":"Popoloca","to":"Vandeño","value":1},
{"from":"Popoluca de la Sierra","to":"Vandeño","value":1},
{"from":"Purhépecha","to":"Vandeño","value":1},
{"from":"Q'Anjob'Al","to":"Vandeño","value":1},
{"from":"Q'Eqchi'","to":"Vandeño","value":1},
{"from":"Sayulteco","to":"Vandeño","value":1},
{"from":"Tarahumara","to":"Vandeño","value":1},
{"from":"Tecuate","to":"Vandeño","value":1},
{"from":"Teko","to":"Vandeño","value":1},
{"from":"Tepehua","to":"Vandeño","value":1},
{"from":"Tepehuano del sur","to":"Vandeño","value":1},
{"from":"Texistepequeño","to":"Vandeño","value":1},
{"from":"Tlahuica","to":"Vandeño","value":1},
{"from":"Tlapaneco","to":"Vandeño","value":1},
{"from":"Tojolabal","to":"Vandeño","value":1},
{"from":"Totonaco","to":"Vandeño","value":1},
{"from":"Triqui","to":"Vandeño","value":1},
{"from":"Tseltal","to":"Vandeño","value":1},
{"from":"Tzotzil","to":"Vandeño","value":1},
{"from":"Yaqui","to":"Vandeño","value":1},
{"from":"Zapoteco","to":"Vandeño","value":1},
{"from":"Zoque","to":"Vandeño","value":1},
{"from":"Chichimeca","to":"Zamorano Amarillo","value":1},
{"from":"Cora","to":"Zamorano Amarillo","value":1},
{"from":"Huichol","to":"Zamorano Amarillo","value":1},
{"from":"Nahua","to":"Zamorano Amarillo","value":1},
{"from":"Otomí","to":"Zamorano Amarillo","value":1},
{"from":"Purhépecha","to":"Zamorano Amarillo","value":1},
{"from":"Akateko","to":"Zapalote Chico","value":1},
{"from":"Amuzgo","to":"Zapalote Chico","value":1},
{"from":"Awakateko","to":"Zapalote Chico","value":1},
{"from":"Ch'ol","to":"Zapalote Chico","value":1},
{"from":"Chatino","to":"Zapalote Chico","value":1},
{"from":"Chontal de Oaxaca","to":"Zapalote Chico","value":1},
{"from":"Chuj","to":"Zapalote Chico","value":1},
{"from":"Huave","to":"Zapalote Chico","value":1},
{"from":"Ixil","to":"Zapalote Chico","value":1},
{"from":"Jakalteko","to":"Zapalote Chico","value":1},
{"from":"K'iche'","to":"Zapalote Chico","value":1},
{"from":"Kaqchikel","to":"Zapalote Chico","value":1},
{"from":"Lacandón","to":"Zapalote Chico","value":1},
{"from":"Mame","to":"Zapalote Chico","value":1},
{"from":"Maya","to":"Zapalote Chico","value":1},
{"from":"Mixe","to":"Zapalote Chico","value":1},
{"from":"Q'Anjob'Al","to":"Zapalote Chico","value":1},
{"from":"Q'Eqchi'","to":"Zapalote Chico","value":1},
{"from":"Tecuate","to":"Zapalote Chico","value":1},
{"from":"Teko","to":"Zapalote Chico","value":1},
{"from":"Tlapaneco","to":"Zapalote Chico","value":1},
{"from":"Tojolabal","to":"Zapalote Chico","value":1},
{"from":"Triqui","to":"Zapalote Chico","value":1},
{"from":"Tseltal","to":"Zapalote Chico","value":1},
{"from":"Tzotzil","to":"Zapalote Chico","value":1},
{"from":"Zapoteco","to":"Zapalote Chico","value":1},
{"from":"Zoque","to":"Zapalote Chico","value":1},
{"from":"Akateko","to":"Zapalote Grande","value":1},
{"from":"Amuzgo","to":"Zapalote Grande","value":1},
{"from":"Awakateko","to":"Zapalote Grande","value":1},
{"from":"Ayapaneco","to":"Zapalote Grande","value":1},
{"from":"Ch'ol","to":"Zapalote Grande","value":1},
{"from":"Chatino","to":"Zapalote Grande","value":1},
{"from":"Chinanteco","to":"Zapalote Grande","value":1},
{"from":"Chocholteco","to":"Zapalote Grande","value":1},
{"from":"Chontal de Oaxaca","to":"Zapalote Grande","value":1},
{"from":"Chontal de Tabasco","to":"Zapalote Grande","value":1},
{"from":"Chuj","to":"Zapalote Grande","value":1},
{"from":"Cuicateco","to":"Zapalote Grande","value":1},
{"from":"Huave","to":"Zapalote Grande","value":1},
{"from":"Ixcateco","to":"Zapalote Grande","value":1},
{"from":"Ixil","to":"Zapalote Grande","value":1},
{"from":"Jakalteko","to":"Zapalote Grande","value":1},
{"from":"K'iche'","to":"Zapalote Grande","value":1},
{"from":"Kaqchikel","to":"Zapalote Grande","value":1},
{"from":"Lacandón","to":"Zapalote Grande","value":1},
{"from":"Mame","to":"Zapalote Grande","value":1},
{"from":"Maya","to":"Zapalote Grande","value":1},
{"from":"Mazateco","to":"Zapalote Grande","value":1},
{"from":"Mixe","to":"Zapalote Grande","value":1},
{"from":"Nahua","to":"Zapalote Grande","value":1},
{"from":"Oluteco","to":"Zapalote Grande","value":1},
{"from":"Otomí","to":"Zapalote Grande","value":1},
{"from":"Popoloca","to":"Zapalote Grande","value":1},
{"from":"Popoluca de la Sierra","to":"Zapalote Grande","value":1},
{"from":"Q'Anjob'Al","to":"Zapalote Grande","value":1},
{"from":"Q'Eqchi'","to":"Zapalote Grande","value":1},
{"from":"Sayulteco","to":"Zapalote Grande","value":1},
{"from":"Tecuate","to":"Zapalote Grande","value":1},
{"from":"Teko","to":"Zapalote Grande","value":1},
{"from":"Texistepequeño","to":"Zapalote Grande","value":1},
{"from":"Tlapaneco","to":"Zapalote Grande","value":1},
{"from":"Tojolabal","to":"Zapalote Grande","value":1},
{"from":"Totonaco","to":"Zapalote Grande","value":1},
{"from":"Triqui","to":"Zapalote Grande","value":1},
{"from":"Tseltal","to":"Zapalote Grande","value":1},
{"from":"Tzotzil","to":"Zapalote Grande","value":1},
{"from":"Zapoteco","to":"Zapalote Grande","value":1},
{"from":"Zoque","to":"Zapalote Grande","value":1}


]



chart.dataFields.fromName = "from";
chart.dataFields.toName = "to";
chart.dataFields.value = "value";


chart.nodePadding = 1;
chart.minNodeSize = 0.001;
chart.startAngle = 60;
chart.endAngle = chart.startAngle + 360;
chart.sortBy = "";


var nodeTemplate = chart.nodes.template;
nodeTemplate.readerTitle = "";
nodeTemplate.showSystemTooltip = true;
nodeTemplate.propertyFields.fill = "color";
nodeTemplate.tooltipText = "{name}"+" interactua con "+"{total}";

// when rolled over the node, make all the links rolled-over
nodeTemplate.events.on("over", function (event) {    
    var node = event.target;
    node.outgoingDataItems.each(function (dataItem) {
        if(dataItem.toNode){
            dataItem.link.isHover = true;
            dataItem.toNode.label.isHover = true;
        }
    })
    node.incomingDataItems.each(function (dataItem) {
        if(dataItem.fromNode){
            dataItem.link.isHover = true;
            dataItem.fromNode.label.isHover = true;
        }
    }) 

    node.label.isHover = true;

let slice = chart.nodes.template.slice;
slice.stroke = am4core.color("#000");
slice.strokeOpacity = 0.5;
slice.strokeWidth = 1;
slice.cornerRadius = 8;
slice.innerCornerRadius = .01;  
})

// when rolled out from the node, make all the links rolled-out
nodeTemplate.events.on("out", function (event) {
    var node = event.target;
    node.outgoingDataItems.each(function (dataItem) {        
        if(dataItem.toNode){
            dataItem.link.isHover = false;                
            dataItem.toNode.label.isHover = false;
        }
    })
    node.incomingDataItems.each(function (dataItem) {
        if(dataItem.fromNode){
            dataItem.link.isHover = false;
           dataItem.fromNode.label.isHover = false;
        }
    })

    node.label.isHover = false;
})

var label = nodeTemplate.label;
label.relativeRotation = 90;

label.fillOpacity = 0.35;
var labelHS = label.states.create("hover");
labelHS.properties.fillOpacity = 1;

nodeTemplate.cursorOverStyle = am4core.MouseCursorStyle.pointer;
// this adapter makes non-main character nodes to be filled with color of the main character which he/she kissed most
/*nodeTemplate.adapter.add("fill", function (fill, target) {
    var node = target;
    var counters = {};
    var mainChar = false;
    node.incomingDataItems.each(function (dataItem) {
        if(colors[dataItem.toName]){
            mainChar = true;
        }

        if(isNaN(counters[dataItem.fromName])){
            counters[dataItem.fromName] = dataItem.value;
        }
        else{
            counters[dataItem.fromName] += dataItem.value;
        }
    })
    if(mainChar){
        return fill;
    }

    var count = 0;
    var color;
    var biggest = 0;
    var biggestName;

    for(var name in counters){
        if(counters[name] > biggest){
            biggestName = name;
            biggest = counters[name]; 
        }        
    }
    if(colors[biggestName]){
        fill = colors[biggestName];
    }
  
    return fill;
})*/

// link template
var linkTemplate = chart.links.template;
linkTemplate.strokeOpacity = 0;
linkTemplate.fillOpacity = 0.1;

var hoverState = linkTemplate.states.create("hover");
hoverState.properties.fillOpacity = 0.7;
hoverState.properties.strokeOpacity = 0.7;

// data credit label
/*var creditLabel = chart.chartContainer.createChild(am4core.TextLink);
creditLabel.text = "Data source: notrudedude";
creditLabel.url = "https://www.reddit.com/user/notrudedude";
creditLabel.y = am4core.percent(99);
creditLabel.x = am4core.percent(99);
creditLabel.horizontalCenter = "right";
creditLabel.verticalCenter = "bottom";*/



            chart.exporting.menu = new am4core.ExportMenu();
            chart.exporting.menu.items = [{
                "label": "...",
                "menu": [
                    {
                        "label": "Imagen",
                        "menu": [
                            { "type": "png", "label": "PNG" },
                            { "type": "jpg", "label": "JPG" },
                            { "type": "gif", "label": "GIF" },
                            { "type": "pdf", "label": "PDF" }
                        ]
                    }, 
                    {
                        "label": "Imprimir", "type": "print"
                    }
                ]
            }];
            